
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring
  annotations:
    tektonci/build-namespace: spring
    backstage.io/kubernetes-id: spring
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: nos-og/spring
spec:
  type: api
  system: system:default/demo
  lifecycle: production
  owner: masanara
