apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: spring-pipeline-run-init
  namespace: spring
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    tekton.dev/pipeline: spring-pipeline
    type: pipeline
spec:
  params:
    - name: source-repo
      value: 'https://github.com/nos-og/spring.git'
    - name: source-branch
      value: main
    - name: output-image
      value: quay.io/hello/spring
  pipelineRef:
    name: spring-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
